### ISSUE TITLE
Documentation: Add example of using NetBox Inventory plugin (CLI and AWX/Tower)

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#169]
##### ISSUE TYPE

 - Documentation update

##### SUMMARY

Need to add examples on how to use the inventory plugin via CLI and AWX/Tower to README

**Comment by bluikko** [comment]
What is the scope for this documentation? I guess I could have a try it since I'm going to test moving to netbox-community on the AWX inventory and I'm very familiar with creating documentation.

- Installation of netbox-community under AWX? I'm using the RPM builds of AWX so if this is needed I don't think I can help for the official Docker AWX.
- Configuring/adding inventory script in AWX webui?
- Or simply which YAML file to give to `ansible-inventory` when using netbox-community?

`nb_inventory.py` has already examples so that's why I'm asking for clarification, it implies that you're possibly looking for more than just the YAML file contents.

**Comment by FragmentedPacket** [comment]
Probably all three of those. Very basic walk-throughs on what should be in the YAML file, how to create inventory within AWX/Tower using the same YAML file, etc.
