### ISSUE TITLE
Update modules to work with pynetbox >5.0.0

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#248]
##### ISSUE TYPE

 - Bug Report

Need to change the way the `self.nb` object is created due to changes in Pynetbox 5.0.0

**Comment by jvanderaa** [comment]
Are we getting a bunch of benefit out of using pynetbox? Would it be worth looking at moving to just using requests, preventing the need for urgent refactoring? Since it looks like the new method requires a pre-built session instead of establishing one within the SDK.

Just a question, not sure of what it would look like at the moment. I have some work where I do need to do something similar, but probably on a small scale.

**Comment by FragmentedPacket** [comment]
It would take a lot of work to refactor the code and tests for this so not sure it's worth it at this point, but possibly sometime in the future to remove the dependency on an external SDK would probably be ideal, although, it is nice to have some of the built-in capabilities that come with `pynetbox`.
