### ISSUE TITLE
remove constants, use the _choices api instead..

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#67]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Replace the pre-defined constants in netbox_utils.py, for example:

IP_ADDRESS_STATUS
IP_ADDRESS_ROLE
RACK_TYPE
INTF_FORM_FACTOR 
INTF_MODE

by using the _choices api.

ie, to get all the choices from dcim, you an do:

http://api-url/api/dcim/_choices (or using pynetbox - dcim_choicse = nb.dcim.choices())

and it will give all the choices.

This is need because netbox-2.7 replaces many of the numeric constants with "slugs"/human readable values, and in netbox-2.8, the numeric constants will no longer be honored..

If you use the _choices api, you will also maintain compatibility with netbox-2.6 (since it also supports the choices api)

**Comment by FragmentedPacket** [comment]
Thanks for raising this issue! I actually just spoke to Jeremy Stretch about the changes in 2.7 last week and this is the solution that seems to make the most sense moving forward at this time and is on my radar.

I'm hoping to get this implemented soon, but no ETA. If you'd like to take a stab at this, that would be great. I was thinking of making the choices properties on the NetboxModule class.

**Comment by FragmentedPacket** [comment]
Just an update, I have a branch `change-choices` that implements the changes, but due to the way `pynetbox` serializes the object, it checks for the `id` of the object instead of the `value`.

I've submitted the following PR that would allow us to pass in a list on how we want to have the nested objects serialized: https://github.com/digitalocean/pynetbox/pull/222. Some of the details are in this, but I can definitely implement the changes once 2.8 rolls around and we won't have any issues doing so.
